PhotoAlbum/Models/Shared/AuthorViewModel.cs
using System;

namespace PhotoAlbum.Models.Shared
{
    /// <summary>
    /// Represents post author view model.
    /// </summary>
    public sealed class AuthorViewModel
    {
        /// <summary>
        /// Gets or sets author identifier.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets first name.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets last name.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets profile photo identifier.
        /// </summary>
        public Guid? ProfilePhotoId { get; set; }
    }
}

PhotoAlbum/Models/Shared/SimplePaginationViewModel.cs
namespace PhotoAlbum.Models.Shared
{
    /// <summary>
    ///     Represents pagination view model.
    /// </summary>
    public sealed class SimplePaginationViewModel
    {
        /// <summary>
        ///     Gets or sets number of total pages.
        /// </summary>
        public int TotalPages { get; set; }

        /// <summary>
        ///     Gets or sets current pages.
        /// </summary>
        public int CurrentPage { get; set; }

        /// <summary>
        ///     Gets or sets next pages url.
        /// </summary>
        public string NextUrl { get; set; }

        /// <summary>
        ///     Gets or sets previous pages url.
        /// </summary>
        public string PreviousUrl { get; set; }
    }
}

PhotoAlbum/Models/Shared/UserAvatarViewModel.cs
using System;

namespace PhotoAlbum.Models.Shared
{
    /// <summary>
    ///     Represents user avatar view model.
    /// </summary>
    public sealed class UserAvatarViewModel 
    {
        /// <summary>
        ///     Gets or sets photo identifier.
        /// </summary>
        public Guid? PhotoId { get; set; }
    }
}

PhotoAlbum/Controllers/CultureController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using PhotoAlbum.Filters;
using PhotoAlbum.Helpers;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents culture controller.
    /// </summary>
    public sealed class CultureController : BaseController
    {
        /// <summary>
        ///     Changes the culture.
        /// </summary>
        /// <param name="cultureCode"></param>
        /// <param name="redirectUri"></param>
        /// <returns></returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public ActionResult SetCulture(
            [Required(AllowEmptyStrings = false)] [MaxLength(2)] [MinLength(2)]
            string cultureCode,
            [Required(AllowEmptyStrings = false)] Uri redirectUri)
        {
            var culture = CultureManager.GetImplementedCulture(cultureCode);

            var cultureCookie = Request.Cookies[CultureManager.CultureCookieName];

            if (cultureCookie != null)
            {
                cultureCookie.Value = culture;
            }
            else
            {
                cultureCookie = new HttpCookie(CultureManager.CultureCookieName)
                {
                    Value = culture,
                    Expires = DateTime.UtcNow.AddYears(1)
                };
            }

            Response.Cookies.Add(cultureCookie);

            return Redirect(redirectUri.ToString());
        }
    }
}

PhotoAlbum/Controllers/ImageController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Services.Interfaces;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents image controller.
    /// </summary>
    [Authorize]
    public sealed class ImageController : BaseController
    {
        private readonly IFileStorage _fileStorage;
        private readonly IImageAccessAuthorizationService _imageAccessAuthorizationService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="ImageController" /> class.
        /// </summary>
        /// <param name="fileStorage">File storage.</param>
        /// <param name="imageAccessAuthorizationService">Image accessing authorization service.</param>
        public ImageController(
            IFileStorage fileStorage,
            IImageAccessAuthorizationService imageAccessAuthorizationService)
        {
            _fileStorage = fileStorage;
            _imageAccessAuthorizationService = imageAccessAuthorizationService;
        }

        /// <summary>
        ///     Gets image.
        /// </summary>
        /// <param name="id">Image identifier.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [OutputCache(Duration = 120)]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> GetImage([Required] Guid? id)
        {
            _imageAccessAuthorizationService.CheckPermissions(id.Value, User);
            return File(await _fileStorage.GetFileStringAsync(id.Value), "image/jpeg");
        }
    }
}

PhotoAlbum/Controllers/LikeController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Services.Interfaces;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents like controller.
    /// </summary>
    [Authorize]
    public sealed class LikeController : BaseController
    {
        private readonly IPostService _postService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="LikeController" /> class.
        /// </summary>
        /// <param name="postService">Post service.</param>
        public LikeController(IPostService postService)
        {
            _postService = postService;
        }

        /// <summary>
        ///     Add a like to the post.
        /// </summary>
        /// <param name="postId">Post identifier.</param>
        /// <param name="redirectUri">Url for redirect.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> LikePost([Required] int? postId, string redirectUri)
        {
            await _postService.LikePostByUserAsync(User.Identity.GetUserId(), postId.Value);
            return Redirect(redirectUri);
        }

        /// <summary>
        ///     Delete a like from the post.
        /// </summary>
        /// <param name="postId">Post identifier.</param>
        /// <param name="redirectUri">Url for redirect.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> UnlikePost([Required] int? postId, string redirectUri)
        {
            // ReSharper disable once PossibleInvalidOperationException
            await _postService.UnlikePostByUserAsync(User.Identity.GetUserId(), postId.Value);
            return Redirect(redirectUri);
        }
    }
}

PhotoAlbum/Controllers/PostController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Infrastructure.Helpers;
using PhotoAlbum.Models;
using PhotoAlbum.Models.Post;
using PhotoAlbum.Models.User;
using PhotoAlbum.Services.Interfaces;
using PhotoAlbum.Services.Models;
using PhotoAlbum.Services.Models.Post;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents post controller.
    /// </summary>
    [Authorize]
    public sealed class PostController : BaseController
    {
        private readonly IAlbumService _albumService;
        private readonly IMapper _mapper;
        private readonly IPostService _postService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="PostController" /> class.
        /// </summary>
        /// <param name="albumService">Album service.</param>
        /// <param name="postService">Post service.</param>
        /// <param name="mapper">Mapper.</param>
        public PostController(
            IAlbumService albumService,
            IPostService postService,
            IMapper mapper)
        {
            _albumService = albumService;
            _postService = postService;
            _mapper = mapper;
        }

        /// <summary>
        ///     Returns form for creating post.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        public async Task<ActionResult> GetCreatePostFormView()
        {
            var createPostAggregatedViewModel = new CreatePostAggregatedViewModel
            {
                Albums = _mapper.Map<AlbumPreviewViewModel[]>(
                    await _albumService.GetUserAlbumsAsync(User))
            };

            return View("CreatePostFormView", createPostAggregatedViewModel);
        }

        /// <summary>
        ///     Performs post creating.
        /// </summary>
        /// <param name="createPostViewModel">Creating post view model.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpPost]
        public async Task<ActionResult> CreatePost([Required] CreatePostViewModel createPostViewModel)
        {
            if (!ModelState.IsValid)
            {
                var createPostAggregatedViewModel = new CreatePostAggregatedViewModel
                {
                    Albums = _mapper.Map<AlbumPreviewViewModel[]>(
                        await _albumService.GetUserAlbumsAsync(User))
                };

                return View("CreatePostFormView", createPostAggregatedViewModel);
            }

            var createdPost = await _postService.CreatePostAsync(
                _mapper.Map<CreatePostDto>(createPostViewModel),
                User.Identity.GetUserId());

            return RedirectToAction("GetDetailedPostView", new {PostId = createdPost.Id});
        }

        /// <summary>
        ///     Returns detailed post information by view.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> GetDetailedPostView(
            [Required] GetFullPostQueryParameters queryParameters)
        {
            return View("PostDetailedView", _mapper.Map<FullPostViewModel>(
                await _postService.GetFullPostAsync(
                    new GetFullPostQueryParametersDto
                    {
                        RequestingUserId = User.Identity.GetUserId(),
                        PostId = queryParameters.PostId.Value,
                        RequestingUserRoles = User.Identity.GetClaim(ClaimNamesConstants.RolesClaimName).Split(','),
                        PaginationParameters = new GetPaginationQueryParametersDto
                        {
                            PageSize = queryParameters.PageSize.Value,
                            PageNumber = queryParameters.PageNumber.Value 
                        }
                    })));
        }
    }
}

PhotoAlbum/Views/Shared/AlbumPreviewPartial.cshtml
@model PhotoAlbum.Models.User.AlbumPreviewViewModel

<div class="d-flex flex-wrap flex-column justify-content-around overflow-hidden my-2 ph-album-preview">
    <!-- Preview -->
    <div class="d-flex justify-content-center image img-thumbnail rounded-circle m-auto ph-album-preview-photo"
         style="background-image: url('@Url.Action("GetImage", "Image", new {id = Model.PreviewPhotoId})'), url('./../../Content/imgs/no-photo.svg')">
    </div>
    <!-- Title -->
    <div class="d-block text-truncate ph-album-preview-title text-center">
        <small class="text-break">@Html.DisplayFor(model => model.Title)</small>
    </div>
</div>

PhotoAlbum/Views/Shared/CommentsListPartial.cshtml
@model PhotoAlbum.Models.PaginatedViewModel<PhotoAlbum.Models.Post.CommentViewModel>

<div class="d-flex flex-column py-2">
    @foreach (var comment in Model.Items)
    {
        <div class="d-flex flex-row">
            <div class="d-inline-block mr-2">
                <strong>@Html.ActionLink($"{comment.FirstName} {comment.LastName}", "GetDetailedUserView", new { UserId = comment.AuthorId, controller = "User" }, new { @class = "text-truncate text-decoration-none text-dark" })</strong> 
                @comment.Content
            </div>
        </div>
    }
</div>

PhotoAlbum/Views/Shared/NoItems.cshtml
@model string[]

<div class="d-flex justify-content-center my-4">
    <div class="d-flex flex-column">
        <div class="d-flex justify-content-center">
            <img class="ph-info-icon" src="~/Content/imgs/empty.svg" alt="Empty"/>
        </div>
        <div class="d-flex justify-content-center">
            <h4>@Model[0]</h4>
        </div>
        @if (Model.Length == 2)
        {
            <div class="d-flex justify-content-center">
                <small class="text-muted">@Model[1]</small>
            </div>
        }
    </div>
</div>

PhotoAlbum/Views/Shared/PhotosCarouselPreviewPartial.cshtml
@model IList<PhotoAlbum.Models.User.PhotoMetadataPreviewViewModel> 

<div id="carouselExampleControls" class="carousel slide d-flex flex-fill m-auto border overflow-hidden" data-ride="carousel">
    <div class="carousel-inner">
        @for (var index = 0; index < Model.Count; index++)
        {
            <div class="ph-load-photo-preview carousel-item @(index == 0 ? "active": "")">
                <img src="@Url.Action("GetImage", "Image", new {id = Model[index].FileId})" class="d-block w-100" alt="@index post photo."/>
            </div>
        }
    </div>
    @if (Model.Count > 1)
    {
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    }
</div>

PhotoAlbum/Views/Shared/PostListPartial.cshtml
@using PhotoAlbum.Models.Shared
@model PhotoAlbum.Models.Post.PreviewPostListAggregatedModel

@if (!Model.Posts.Items.Any())
{
    @Html.Partial("NoItems", new[] { "No posts" })
}
else
{
    <div class="ph-500-width m-auto">
        <nav class="d-flex justify-content-between navbar navbar-light bg-light">
            <div class="d-flex btn-group mb-1">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @PostListResources.SortOrder
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("GetExploreView", "Explore", new {SortOrder = "date:desc"})">
                        @PostListResources.SortByDescending
                        <i class="fas fa-arrow-down"></i>
                    </a>
                    <a class="dropdown-item" href="@Url.Action("GetExploreView", "Explore", new {SortOrder = "date:asc"})">
                        @PostListResources.SortByAscending
                        <i class="fas fa-arrow-up"></i>
                    </a>
                </div>
            </div>
            @using (Html.BeginForm("GetExploreView", "Explore", FormMethod.Get, new { @class = "d-flex form-inline" }))
            {
                @Html.AntiForgeryToken()
                @Html.TextBoxFor(model => model.QueryParameters.SearchText, null, new { @class = "form-control mb-1 mr-sm-2", type = "search", placeholder = @PostListResources.SearchTextPlaceholder })
                @Html.ValidationMessageFor(model => model.QueryParameters.SearchText)
                <button class="btn btn btn-outline-secondary my-2 my-sm-0" type="submit">@PostListResources.ButtonSearch</button>
            }
        </nav>
        @foreach (var post in Model.Posts.Items)
        {
            <a name="Post_@post.Post.Id"></a>
            <div class="d-flex flex-column justify-content-center mb-4">
                <!-- Author preview -->
                <div class="d-flex flex-row">
                    <div class="pl-2">
                        @Html.Partial("UserAvatartPartial", new UserAvatarViewModel { PhotoId = post.Author.ProfilePhotoId })
                    </div>
                    <div class="d-flex flex-grow-1 flex-column pl-4 justify-content-center">
                        <div class="d-flex">
                            <strong>@Html.ActionLink($"{post.Author.FirstName} {post.Author.LastName}", "GetDetailedUserView", new { UserId = post.Author.Id, controller = "User" }, new { @class = "d-block text-truncate text-decoration-none text-dark" }) </strong>
                        </div>
                        <div class="d-flex">
                            <p class="text-muted">@post.Post.Location</p>
                        </div>
                    </div>
                    <div class="d-flex flex-column py-1 justify-content-center">
                        @if (!post.IsLiked)
                        {
                            <a class="text-dark" href="@Url.Action("LikePost", "Like", new {postId = post.Post.Id, redirectUri = Request.RawUrl + $"#Post_{post.Post.Id}"})">
                                <i class="far fa-heart fa-2x"></i>
                            </a>
                        }
                        else
                        {
                            <a class="text-dark" href="@Url.Action("UnlikePost", "Like", new {postId = post.Post.Id, redirectUri = Request.RawUrl + $"#Post_{post.Post.Id}"})">
                                <i class="fas fa-heart fa-2x"></i>
                            </a>
                        }
                        <div class="justify-content-center d-flex">
                            <strong class="m-auto">@post.LikesCount</strong>
                        </div>
                    </div>
                </div>
                <!-- Photos carousel -->
                <div class="ph-load-photo-preview overflow-hidden m-auto">
                    @Html.Partial("PhotosCarouselPreviewPartial", post.Post.Photos)
                </div>
                <!-- Post description -->
                <div class="d-flex flex-column card border-top-0 rounded-0 rounded-bottom mb-3">
                    <div class="card-body py-2">
                        <div class="pb-2">
                            @Html.ActionLink(
                                post.Album.Title,
                                "GetAlbumView",
                                "Album",
                                new { AlbumId = post.Album.Id },
                                new { @class = "d-block text-truncate" })
                            <span class="d-block text-truncate">@post.Post.Description</span>
                        </div>
                        @if (post.Comments.Any())
                        {
                            foreach (var comment in post.Comments)
                            {
                                <div class="d-flex flex-row">
                                    <strong class="mr-1">@Html.ActionLink($"{comment.FirstName} {comment.LastName}", "GetDetailedUserView", "User", new { UserId = comment.AuthorId }, new { @class = "text-truncate text-decoration-none text-dark" })</strong>
                                    @comment.Content
                                </div>
                            }
                            <div class="d-flex mt-2">
                                <small class="text-muted">@Html.ActionLink("View all", "GetDetailedPostView", "Post", new { PostId = post.Post.Id }, new { @class = "text-truncate text-decoration-none text-dark" })</small>
                            </div>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
}

PhotoAlbum/Views/Shared/PostsTiledPartial.cshtml
@model PhotoAlbum.Models.PaginatedViewModel<PhotoAlbum.Models.User.PhotoMetadataPreviewViewModel> 

<div class="d-flex flex-row flex-wrap">
    <div class="card-columns">
        @foreach (var postPreview in Model.Items)
        {
            <a class="card rounded-0" href="@Url.Action("GetDetailedPostView", "Post", new {postPreview.PostId})">
                <img class="card-img-top img-fluid rounded-0" src="@Url.Action("GetImage", "Image", new {id = postPreview.FileId})" alt="Card image cap">
            </a>
        }
    </div>
</div>

PhotoAlbum/Views/Shared/SimplePaginationPartial.cshtml
 @model PhotoAlbum.Models.Shared.SimplePaginationViewModel

<nav class="m-auto">
    <ul class="pagination pagination-sm justify-content-end">
        @if (Model.CurrentPage == 0)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">@SimplePaginationResources.PreviousPage</a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="@Model.PreviousUrl">@SimplePaginationResources.PreviousPage</a>
            </li>
        }

        @if (Model.CurrentPage + 1 < Model.TotalPages)
        {

            <li class="page-item">
                <a class="page-link" href="@Model.NextUrl">@SimplePaginationResources.NextPage</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">@SimplePaginationResources.NextPage</a>
            </li>
        }
    </ul>
</nav>

PhotoAlbum/Views/Shared/UserAvatartPartial.cshtml
@model PhotoAlbum.Models.Shared.UserAvatarViewModel 

<div
    class="ph-user-avatar image"
    style="background-image: url('@Url.Action("GetImage", "Image", new {id = Model.PhotoId})'), url('./../../Content/imgs/default_avatar.svg')">
</div>

PhotoAlbum/Views/Shared/_Layout.cshtml
@using System.Threading
@using Microsoft.AspNet.Identity
@using PhotoAlbum.Controllers
@using PhotoAlbum.Helpers
@using PhotoAlbum.Infrastructure.Helpers
@using PhotoAlbum.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/imgs")
    @Scripts.Render("~/bundles/modernizr")
    <!-- I know it's wrong, but it only one way to solve -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.2/umd/popper.min.js"></script>
</head>
<body>

<nav class="navbar navbar-light navbar-expand bg-light fixed-top">
    <div class="container">
        <!-- Logo -->
        <a class="navbar-brand d-flex flex-row" href="@Url.Action("GetExploreView", "Explore")">
            <h5 class="ph-logo-title">Photogram</h5>
        </a>
        <!-- Main Menu -->
        <div class="d-flex flex-fill justify-content-center">
            @if (User.Identity.IsAuthenticated)
            {
                <a class="d-flex flex-column justify-content-center mx-3 nav-link @((string)Request.RequestContext.RouteData.Values["action"] == nameof(ExploreController.GetFollowingUpdatesAsync)? "text-body" : "text-muted")"
                   href="@Url.Action("GetFollowingUpdatesAsync", "Explore")">
                    <div class="d-flex justify-content-center">
                        <i class="fa fa-camera-retro"></i>
                    </div>
                    <small>@LayoutResources.News</small>
                </a>
                <a class="d-flex flex-column justify-content-center mx-3 nav-link @((string)Request.RequestContext.RouteData.Values["action"] == nameof(ExploreController.GetExploreView)? "text-body" : "text-muted")"
                   href="@Url.Action("GetExploreView", "Explore")">
                    <div class="d-flex justify-content-center">
                        <i class="fa fa-search"></i>
                    </div>
                    <small>@LayoutResources.Explore</small>
                </a>
                <a class="d-flex flex-column justify-content-center mx-3 nav-link @((string)Request.RequestContext.RouteData.Values["action"] == nameof(AlbumController.GetUserAlbumsView)? "text-body" : "text-muted")"
                   href="@Url.Action(nameof(AlbumController.GetUserAlbumsView), "Album", new {UserId = User.Identity.GetUserId()})">
                    <div class="d-flex justify-content-center">
                        <i class="far fa-clone"></i>
                    </div>
                    <small>@LayoutResources.Albums</small>
                </a>
                if (User.IsInRole("Administrator"))
                {
                    <a class="d-flex flex-column justify-content-center mx-3 nav-link @((string)Request.RequestContext.RouteData.Values["action"] == nameof(UserController.GetUserManagementListView)? "text-body" : "text-muted")"
                       href="@Url.Action("GetUserManagementListView", "User")">
                        <div class="d-flex justify-content-center">
                            <i class="far fa-user"></i>
                        </div>
                        <small>@LayoutResources.Users</small>
                    </a>
                }
            }
        </div>
        <!-- Profile Preview -->
        @if (User.Identity.IsAuthenticated)
        {
            <div class="ml-auto @(User.Identity.IsAuthenticated ? "mr-2": "")">
                <div class="dropdown">
                    <div
                        class="ph-user-sm-avatar image img-thumbnail"
                        id="profileDropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                        style="background-image: url('@Url.Action("GetImage", "Image", new {id = User.Identity.GetClaim(ClaimNamesConstants.AvatarClaimName)})'), url('./../../Content/imgs/default_avatar.svg')">
                    </div>
                    <div class="dropdown-menu" id="ph-profile-drop-down-menu" aria-labelledby="profileDropdown">
                        @Html.ActionLink(LayoutResources.Profile, "GetDetailedUserView", new {UserId = User.Identity.GetUserId(), controller = "User"}, new {@class = "dropdown-item"})
                        @Html.ActionLink(LayoutResources.Settings, "GetSettingsView", new {controller = "User"}, new {@class = "dropdown-item"})
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink(LayoutResources.Logout, "Logout", new {controller = "Account"}, new {@class = "dropdown-item"})
                    </div>
                </div>
            </div>
        }
        <ul class="navbar-nav ml-auto @(User.Identity.IsAuthenticated ? "border-left": "")">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="cultures" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @CultureManager.CurrentCulture.TwoLetterName.ToUpper()
                    <img class="ph-culture-img" src="~/Content/imgs/cultures/@CultureManager.CurrentCulture.Image" alt="@CultureManager.CurrentCulture.FullName"/>
                </a>
                <div class="dropdown-menu" aria-labelledby="cultures">
                    @foreach (var supportedCulture in CultureManager.SupportedCultures
                        .Where(supportedCulture => supportedCulture.TwoLetterName != Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName))
                    {
                        <a class="nav-link"
                           href="@Url.Action("SetCulture", "Culture", new RouteValueDictionary {["cultureCode"] = supportedCulture.TwoLetterName, ["redirectUri"] = Request.Url})">
                            @supportedCulture.TwoLetterName.ToUpper()
                            <img class="ph-culture-img" src="~/Content/imgs/cultures/@supportedCulture.Image" alt="@supportedCulture.FullName"/>
                        </a>
                    }
                </div>
            </li>
        </ul>
    </div>
</nav>

<div class="body-content pt-5 mt-5 h-100">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryval")
@RenderSection("scripts", false)

</body>
</html>