PhotoAlbum/Models/Post/CommentViewModel.cs
namespace PhotoAlbum.Models.Post
{
    /// <summary>
    ///     Represents comment view model.
    /// </summary>
    public sealed class CommentViewModel
    {
        /// <summary>
        ///     Gets or sets comment identifier.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        ///     Gets or sets author identifier.
        /// </summary>
        public string AuthorId { get; set; }

        /// <summary>
        ///     Gets or sets author first name.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        ///     Gets or sets author last name.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        ///     Gets or sets content.
        /// </summary>
        public string Content { get; set; }
    }
}

PhotoAlbum/Models/Post/CreatePostAggregatedViewModel.cs
using PhotoAlbum.Models.User;

namespace PhotoAlbum.Models.Post
{
    /// <summary>
    ///     Represents creating post aggregated view model.
    /// </summary>
    public sealed class CreatePostAggregatedViewModel
    {
        /// <summary>
        ///     Gets or sets post creating form.
        /// </summary>
        public CreatePostViewModel CreatePost { get; set; }

        /// <summary>
        ///     Gets or sets album preview.
        /// </summary>
        public AlbumPreviewViewModel[] Albums { get; set; }
    }
}

PhotoAlbum/Models/Post/GetFullPostQueryParameters.cs
using System.ComponentModel.DataAnnotations;
using PhotoAlbum.Resources;

namespace PhotoAlbum.Models.Post
{
    /// <summary>
    ///     Represents full post query parameters.
    /// </summary>
    public sealed class GetFullPostQueryParameters
    {
        /// <summary>
        ///     Gets or sets user identifier.
        /// </summary>
        [Required(
            AllowEmptyStrings = false,
            ErrorMessageResourceType = typeof(PostDetailedResources),
            ErrorMessageResourceName = "PostIdRequired")]
        public int? PostId { get; set; }

        /// <summary>
        ///     Gets or sets page number.
        /// </summary>
        [Range(0, int.MaxValue,
            ErrorMessageResourceType = typeof(PostDetailedResources),
            ErrorMessageResourceName = "PageNumberRange")]
        public int? PageNumber { get; set; } = 0;

        /// <summary>
        ///     Gets or sets page size.
        /// </summary>
        [Range(1, 21,
            ErrorMessageResourceType = typeof(PostDetailedResources),
            ErrorMessageResourceName = "PageSizeRange")]
        public int? PageSize { get; set; } = 10;
    }
}

PhotoAlbum/Controllers/AlbumController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Infrastructure.Helpers;
using PhotoAlbum.Models;
using PhotoAlbum.Models.Album;
using PhotoAlbum.Services.Interfaces;
using PhotoAlbum.Services.Models;
using PhotoAlbum.Services.Models.Album;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents album controller.
    /// </summary>
    [Authorize]
    public sealed class AlbumController : BaseController
    {
        private readonly IAlbumService _albumService;
        private readonly IMapper _mapper;

        /// <summary>
        ///     Initializes a new instance of the <see cref="AlbumController" /> class.
        /// </summary>
        /// <param name="albumService">Album service.</param>
        /// <param name="mapper">Mapper.</param>
        public AlbumController(IAlbumService albumService, IMapper mapper)
        {
            _albumService = albumService;
            _mapper = mapper;
        }

        /// <summary>
        ///     Returns form for creating album.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        public Task<ActionResult> GetCreateAlbumFormView()
        {
            return Task.FromResult<ActionResult>(View("CreateAlbumFormView"));
        }

        /// <summary>
        ///     Performs album creating.
        /// </summary>
        /// <param name="createAlbumViewModel">Creating album view model.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [EnsureModelStateValid("CreateAlbumFormView")]
        public async Task<ActionResult> CreateAlbum([Required] CreateAlbumViewModel createAlbumViewModel)
        {
            var addedAlbum = await _albumService.CreateAlbumAsync(
                _mapper.Map<CreateAlbumDto>(createAlbumViewModel),
                User.Identity.GetUserId());

            return RedirectToAction("GetAlbumView", new {AlbumId = addedAlbum.Id});
        }

        /// <summary>
        ///     Gets all user albums.
        /// </summary>
        /// <param name="queryParameters">Query parameters to get user albums.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> GetUserAlbumsView(
            [Required] GetUserAlbumsQueryParameters queryParameters)
        {
            return View(
                "UserAlbumsView",
                _mapper.Map<UserAlbumsViewModel>(
                    await _albumService.GetUserAlbumsAsync(
                        new GetUserAlbumsQueryParametersDto
                        {
                            RequestingUserId = User.Identity.GetUserId(),
                            UserId = queryParameters.UserId,
                            RequestingUserRoles = User.Identity.GetClaim(ClaimNamesConstants.RolesClaimName).Split(','),
                            AlbumsPaginationQueryParameters = new GetPaginationQueryParametersDto
                            {
                                PageNumber = queryParameters.PageNumber.Value,
                                PageSize = queryParameters.PageSize.Value
                            }
                        })
                ));
        }

        /// <summary>
        ///     Gets an album photos.
        /// </summary>
        /// <param name="queryParameters">Query parameters.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> GetAlbumView(
            [Required] GetAlbumPhotosQueryParameters queryParameters)
        {
            return View(
                "AlbumView",
                _mapper.Map<FullAlbumViewModel>(
                    await _albumService.GetFullAlbumAsync(
                        new GetAlbumQueryParametersDto
                        {
                            RequestingUserId = User.Identity.GetUserId(),
                            AlbumId = queryParameters.AlbumId.Value,
                            RequestingUserRoles = User.Identity.GetClaim(ClaimNamesConstants.RolesClaimName).Split(','),
                            PhotosPaginationQueryParameters = new GetPaginationQueryParametersDto
                            {
                                PageNumber = queryParameters.PageNumber.Value,
                                PageSize = queryParameters.PageSize.Value
                            }
                        })
                ));
        }

        /// <summary>
        ///     Returns edit album form.
        /// </summary>
        /// <param name="albumId">Album identifier to edit.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> GetEditAlbumFormView([Required] int? albumId)
        {
            var album = await _albumService.GetAlbumAsync(albumId.Value);

            return View(
                "EditAlbumFormView",
                _mapper.Map<EditAlbumViewModel>(album));
        }

        /// <summary>
        ///     Edits album.
        /// </summary>
        /// <param name="editAlbum">Album to edit.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpPut]
        [Authorize]
        public async Task<ActionResult> EditAlbum(EditAlbumViewModel editAlbum)
        {
            if (!ModelState.IsValid)
            {
                var albumToEdit = await _albumService.GetAlbumAsync(editAlbum.Id.Value);

                return View(
                    "EditAlbumFormView",
                    _mapper.Map<EditAlbumViewModel>(albumToEdit));
            }

            await _albumService.EditAlbumAsync(_mapper.Map<EditAlbumDto>(editAlbum), User.Identity.GetUserId());

            return RedirectToAction("GetAlbumView", new {AlbumId = editAlbum.Id});
        }
    }
}

PhotoAlbum/Controllers/CommentController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Models.Comment;
using PhotoAlbum.Services.Interfaces;
using PhotoAlbum.Services.Models.Comments;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents comment controller.
    /// </summary>
    [Authorize]
    public sealed class CommentController : BaseController
    {
        private readonly ICommentService _commentService;
        private readonly IMapper _mapper;

        /// <summary>
        ///     Initializes a new instance of the <see cref="CommentController" /> class.
        /// </summary>
        /// <param name="commentService">Album service.</param>
        /// <param name="mapper">Mapper.</param>
        public CommentController(ICommentService commentService, IMapper mapper)
        {
            _commentService = commentService;
            _mapper = mapper;
        }

        /// <summary>
        ///     Creates comment.
        /// </summary>
        /// <param name="createComment">Comment to create.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateComment([Required] CreateCommentViewModel createComment)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(
                    "GetErrorOccursView",
                    "Error",
                    new
                    {
                        ErrorMessages = "Invalid entered data.",
                        ReturnUri =
                            createComment.PostId.HasValue
                                ? Url.Action("GetDetailedPostView", "Post", new {createComment.PostId})
                                : Url.Action("GetExploreView", "Explore")
                    });
            }

            await _commentService.CreateCommentAsync(
                _mapper.Map<CreateCommentDto>(createComment),
                User.Identity.GetUserId());

            return RedirectToAction("GetDetailedPostView", "Post", new {createComment.PostId});
        }
    }
}

PhotoAlbum/Controllers/LikeController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Services.Interfaces;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents like controller.
    /// </summary>
    [Authorize]
    public sealed class LikeController : BaseController
    {
        private readonly IPostService _postService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="LikeController" /> class.
        /// </summary>
        /// <param name="postService">Post service.</param>
        public LikeController(IPostService postService)
        {
            _postService = postService;
        }

        /// <summary>
        ///     Add a like to the post.
        /// </summary>
        /// <param name="postId">Post identifier.</param>
        /// <param name="redirectUri">Url for redirect.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> LikePost([Required] int? postId, string redirectUri)
        {
            await _postService.LikePostByUserAsync(User.Identity.GetUserId(), postId.Value);
            return Redirect(redirectUri);
        }

        /// <summary>
        ///     Delete a like from the post.
        /// </summary>
        /// <param name="postId">Post identifier.</param>
        /// <param name="redirectUri">Url for redirect.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> UnlikePost([Required] int? postId, string redirectUri)
        {
            // ReSharper disable once PossibleInvalidOperationException
            await _postService.UnlikePostByUserAsync(User.Identity.GetUserId(), postId.Value);
            return Redirect(redirectUri);
        }
    }
}

PhotoAlbum/Controllers/PostController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Infrastructure.Helpers;
using PhotoAlbum.Models;
using PhotoAlbum.Models.Post;
using PhotoAlbum.Models.User;
using PhotoAlbum.Services.Interfaces;
using PhotoAlbum.Services.Models;
using PhotoAlbum.Services.Models.Post;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents post controller.
    /// </summary>
    [Authorize]
    public sealed class PostController : BaseController
    {
        private readonly IAlbumService _albumService;
        private readonly IMapper _mapper;
        private readonly IPostService _postService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="PostController" /> class.
        /// </summary>
        /// <param name="albumService">Album service.</param>
        /// <param name="postService">Post service.</param>
        /// <param name="mapper">Mapper.</param>
        public PostController(
            IAlbumService albumService,
            IPostService postService,
            IMapper mapper)
        {
            _albumService = albumService;
            _postService = postService;
            _mapper = mapper;
        }

        /// <summary>
        ///     Returns form for creating post.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        public async Task<ActionResult> GetCreatePostFormView()
        {
            var createPostAggregatedViewModel = new CreatePostAggregatedViewModel
            {
                Albums = _mapper.Map<AlbumPreviewViewModel[]>(
                    await _albumService.GetUserAlbumsAsync(User))
            };

            return View("CreatePostFormView", createPostAggregatedViewModel);
        }

        /// <summary>
        ///     Performs post creating.
        /// </summary>
        /// <param name="createPostViewModel">Creating post view model.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpPost]
        public async Task<ActionResult> CreatePost([Required] CreatePostViewModel createPostViewModel)
        {
            if (!ModelState.IsValid)
            {
                var createPostAggregatedViewModel = new CreatePostAggregatedViewModel
                {
                    Albums = _mapper.Map<AlbumPreviewViewModel[]>(
                        await _albumService.GetUserAlbumsAsync(User))
                };

                return View("CreatePostFormView", createPostAggregatedViewModel);
            }

            var createdPost = await _postService.CreatePostAsync(
                _mapper.Map<CreatePostDto>(createPostViewModel),
                User.Identity.GetUserId());

            return RedirectToAction("GetDetailedPostView", new {PostId = createdPost.Id});
        }

        /// <summary>
        ///     Returns detailed post information by view.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        [EnsureModelStateIsValidOtherwiseThrowsError]
        public async Task<ActionResult> GetDetailedPostView(
            [Required] GetFullPostQueryParameters queryParameters)
        {
            return View("PostDetailedView", _mapper.Map<FullPostViewModel>(
                await _postService.GetFullPostAsync(
                    new GetFullPostQueryParametersDto
                    {
                        RequestingUserId = User.Identity.GetUserId(),
                        PostId = queryParameters.PostId.Value,
                        RequestingUserRoles = User.Identity.GetClaim(ClaimNamesConstants.RolesClaimName).Split(','),
                        PaginationParameters = new GetPaginationQueryParametersDto
                        {
                            PageSize = queryParameters.PageSize.Value,
                            PageNumber = queryParameters.PageNumber.Value 
                        }
                    })));
        }
    }
}

PhotoAlbum/Views/Post/CreatePostFormView.cshtml
@model PhotoAlbum.Models.Post.CreatePostAggregatedViewModel
@{
    ViewBag.Title = PageTitles.PostCreating;
}

<div class="d-flex flex-column justify-content-center">
    <div class="d-flex flex-column overflow-hidden m-auto px-1">

        @using (Html.BeginForm("CreatePost", "Post", FormMethod.Post, new {enctype = "multipart/form-data"}))
        {
            <!-- Album Selection -->
            <div class="d-flex overflow-auto py-2 flex-column">
                <div class="d-flex flex-row ph-horizontal-scroll flex-nowrap justify-content-center">
                    @foreach (var album in Model.Albums)
                    {
                        <div class="d-flex flex-column">
                            <div class="d-flex flex-column m-auto mb-2 justify-content-center">
                                <label for="Album_@album.Id" class="ph-album-preview-check px-2">
                                    @Html.RadioButton("AlbumId", album.Id, false, new {id = "Album_" + album.Id})
                                    <div class="ph-album-radio-button p-2 rounded">
                                        @Html.Partial("AlbumPreviewPartial", album)
                                    </div>
                                </label>
                            </div>
                        </div>
                    }
                </div>
            </div>
            @Html.ValidationMessage("AlbumId")
            <!-- Image preview -->
            <div class="d-flex flex-column">
                <label for="file" class="ph-file-upload">
                    <input type="file" id="file" name="Photos" accept=".jpg, .jpeg, .png" onchange="preview(event, 'target1')"/>
                    <div class="ph-image-custom-loader d-flex flex-fill justify-content-center" id="target1">
                        <div class="d-flex text-muted my-5">
                            @CreatePostResources.FirstPhoto
                        </div>
                    </div>
                </label>

                <label for="file2" class="ph-file-upload">
                    <input type="file" id="file2" name="Photos" accept=".jpg, .jpeg, .png" onchange="preview(event, 'target2')"/>
                    <div class="ph-image-custom-loader d-flex flex-fill justify-content-center" id="target2">
                        <div class="d-flex text-muted my-5">
                            @CreatePostResources.SecondPhoto
                        </div>
                    </div>
                </label>

                <label for="file3" class="ph-file-upload">
                    <input type="file" id="file3" name="Photos" accept=".jpg, .jpeg, .png" onchange="preview(event, 'target3')"/>
                    <div class="ph-image-custom-loader d-flex flex-fill justify-content-center" id="target3">
                        <div class="d-flex text-muted my-5">
                            @CreatePostResources.ThirdPhoto
                        </div>
                    </div>
                </label>
                @Html.ValidationMessage("Photos")
                <div class="d-none ph-load-photo-preview overflow-hidden" id="imagePreview">
                    <img class="d-flex" id="imagePreview"/>
                </div>
            </div>

            <!-- Post Information -->
            <div class="form-group">
                @Html.Label(CreatePostResources.NewPostDescription, new {@class = "text-truncate"})
                <div class="col p-0">
                    @Html.TextArea("Description", new {@class = "form-control", rows = 3})
                    @Html.ValidationMessage("Description")
                </div>
            </div>

            <div class="form-group">
                @Html.Label(CreatePostResources.NewPostLocation, new {@class = "text-truncate"})
                <div class="col p-0">
                    @Html.Editor("Location", new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessage("Location")
                </div>
            </div>

            <div class="d-flex mb-5">
                <button type="submit" class="btn btn-primary">@CreatePostResources.CreatingFormOkButton</button>
            </div>
        }
    </div>
</div>

@section scripts {
    <script src="~/Scripts/image-uploader.js"></script>
}

PhotoAlbum/Views/Post/PostDetailedView.cshtml
@using PhotoAlbum.Models.Shared
@model PhotoAlbum.Models.Post.FullPostViewModel

@{
    ViewBag.Title = PageTitles.PostDetails;
}

<div class="d-flex flex-column ph-500-width justify-content-center m-auto mb-4">
    <!-- Author preview -->
    <div class="d-flex flex-row">
        <div class="pl-2">
            @Html.Partial("UserAvatartPartial", new UserAvatarViewModel {PhotoId = Model.Author.ProfilePhotoId})
        </div>
        <div class="d-flex flex-grow-1 flex-column pl-4 justify-content-center">
            <div class="d-flex">
                <strong>@Html.ActionLink($"{Model.Author.FirstName} {Model.Author.LastName}", "GetDetailedUserView", new {UserId = Model.Author.Id, controller = "User"}, new {@class = "d-block text-truncate text-decoration-none text-dark"}) </strong>
            </div>
            <div class="d-flex">
                <p class="text-muted">@Html.DisplayFor(model => model.Location)</p>
            </div>
        </div>
        <div class="d-flex flex-column py-1 justify-content-center">
            <div>
                @if (!Model.IsLiked)
                {
                    <a class="text-dark" href="@Url.Action("LikePost", "Like", new {postId = Model.Id, redirectUri = Request.RawUrl})">
                        <i class="far fa-heart fa-2x"></i>
                    </a>
                }
                else
                {
                    <a class="text-dark" href="@Url.Action("UnlikePost", "Like", new {postId = Model.Id, redirectUri = Request.RawUrl})">
                        <i class="fas fa-heart fa-2x"></i>
                    </a>
                }
            </div>
            <div class="justify-content-center d-flex">
                <strong class="m-auto">@Html.DisplayFor(model => model.LikeCount)</strong>
            </div>
        </div>
    </div>
    <!-- Photos carousel -->
    <div class="ph-load-photo-preview overflow-hidden m-auto">
        @Html.Partial("PhotosCarouselPreviewPartial", Model.Photos)
    </div>
    <!-- Post description and comments -->
    <div class="d-flex flex-column card border-top-0 rounded-0 rounded-bottom mb-3">
        <div class="card-body py-2">
            <div class="pb-2">
                @Html.ActionLink(Model.Album.Title, "GetAlbumView", "Album", new { AlbumId = Model.Album.Id }, new { @class = "d-block text-truncate" })
                <span class="d-block text-truncate">@Html.DisplayFor(model => model.Description)</span>
            </div>
            @if (Model.Comments.Items.Any())
            {
                @Html.Partial("CommentsListPartial", Model.Comments)
            }
            @if (Model.Comments.TotalPages > 1)
            {
                @Html.Partial("SimplePaginationPartial", new SimplePaginationViewModel
                {
                    TotalPages = Model.Comments.TotalPages,
                    CurrentPage = Model.Comments.CurrentPage,
                    NextUrl = Url.Action("GetDetailedPostView", "Post", new { PostId = Model.Id, pageNumber = Model.Comments.CurrentPage + 1 }),
                    PreviousUrl = Url.Action("GetDetailedPostView", "Post", new { PostId = Model.Id, pageNumber = Model.Comments.CurrentPage - 1 })
                })
            }
            <!-- Create comment form -->
            <div class="d-flex ph-comment-post-form border-top">
                @using (Html.BeginForm("CreateComment", "Comment", FormMethod.Post, new { @class = "d-flex flex-row flex-fill" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("PostId", Model.Id)
                    <div class="d-flex flex-grow-1">
                        @Html.TextArea("Content", "", new { @class = "ph-comment-content-input d-flex flex-grow-1", placeholder = @PostDetailedResources.CommentPlaceholder, rows = 1 })
                        @Html.ValidationMessage("Content")
                    </div>

                    <div class="d-flex pr-2">
                        <button type="submit" class="text-primary ph-button-as-link">@PostDetailedResources.SendComment</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>