PhotoAlbum/Controllers/ExploreController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;
using PhotoAlbum.Models;
using PhotoAlbum.Models.Post;
using PhotoAlbum.Services.Interfaces;
using PhotoAlbum.Services.Models;
using PhotoAlbum.Services.Models.Post;

namespace PhotoAlbum.Controllers
{
    /// <summary>
    ///     Represents explore controller.
    /// </summary>
    [Authorize]
    public sealed class ExploreController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IPostService _postService;

        /// <summary>
        ///     Initializes a new instance of the <see cref="ExploreController" /> class.
        /// </summary>
        /// <param name="postService">Post service.</param>
        /// <param name="mapper">Mapper.</param>
        public ExploreController(IPostService postService, IMapper mapper)
        {
            _postService = postService;
            _mapper = mapper;
        }

        /// <summary>
        ///     Returns explore view.
        /// </summary>
        /// <param name="queryParameters">Query parameters.</param>
        /// <returns>A <see cref="Task" /> representing asynchronous action result.</returns>
        [HttpGet]
        public async Task<ActionResult> GetExploreView(GetPostsListQueryParameters queryParameters)
        {
            var resultPosts = await _postService.GetExplorePostsAsync(new GetFollowingPostsQueryParametersDto
            {
                SearchText = queryParameters.SearchText,
                Sort = queryParameters.SortOrder,
                RequestingUserId = User.Identity.GetUserId(),
                PaginationQueryParameters = new GetPaginationQueryParametersDto
                {
                    PageSize = queryParameters.PageSize.Value,
                    PageNumber = queryParameters.PageNumber.Value
                }
            });

            return View("PostListView", new PreviewPostListAggregatedModel
            {
                Posts = _mapper.Map<PaginatedViewModel<PreviewPostAggregatedViewModel>>(resultPosts),
                QueryParameters = queryParameters
            });
        }

        /// <summary>
        ///     Returns following updates view.
        /// </summary>
        /// <param name="queryParameters">Query parameters.</param>
        /// <returns>A <see cref="Task"/> representing asynchronous unit test.</returns>
        [HttpGet]
        [EnsureModelStateValid("FollowingPostListView")]
        public async Task<ActionResult> GetFollowingUpdatesAsync([Required] GetPostsListQueryParameters queryParameters)
        {
            var posts = await _postService.GetFollowingUpdatesAsync(new GetFollowingPostsQueryParametersDto
            {
                SearchText = queryParameters.SearchText,
                RequestingUserId = User.Identity.GetUserId(),
                Sort = queryParameters.SortOrder,
                PaginationQueryParameters = new GetPaginationQueryParametersDto
                {
                    PageSize = queryParameters.PageSize.Value,
                    PageNumber = queryParameters.PageNumber.Value 
                }
            });

            return View("FollowingPostListView", new PreviewPostListAggregatedModel
            {
                Posts = _mapper.Map<PaginatedViewModel<PreviewPostAggregatedViewModel>>(posts),
                QueryParameters = queryParameters
            });
        }
    }
}

PhotoAlbum/Views/Explore/FollowingPostListView.cshtml
@using PhotoAlbum.Models.Shared
@model PhotoAlbum.Models.Post.PreviewPostListAggregatedModel

@{
    ViewBag.Title = PageTitles.News;
}

@Html.Partial("PostListPartial", Model)

<div class="ph-500-width m-auto">
    <div class="d-flex flex-column justify-content-center m-auto mb-4 mt-3">
        @if (Model.Posts.TotalPages > 1)
        {
            @Html.Partial("SimplePaginationPartial", new SimplePaginationViewModel
            {
                TotalPages = Model.Posts.TotalPages,
                CurrentPage = Model.Posts.CurrentPage,
                NextUrl = Url.Action("GetFollowingUpdatesAsync", "Explore", new { pageNumber = Model.Posts.CurrentPage + 1 }),
                PreviousUrl = Url.Action("GetFollowingUpdatesAsync", "Explore", new { pageNumber = Model.Posts.CurrentPage - 1 })
            })
        }
    </div>
</div>

PhotoAlbum/Views/Explore/PostListView.cshtml
@using PhotoAlbum.Models.Shared
@model PhotoAlbum.Models.Post.PreviewPostListAggregatedModel

@{
    ViewBag.Title = PageTitles.Explore;
}

@Html.Partial("PostListPartial", Model)

<div class="ph-500-width m-auto">
    <div class="d-flex flex-column justify-content-center m-auto mb-4 mt-3">
        @if (Model.Posts.TotalPages > 1)
        {
            @Html.Partial("SimplePaginationPartial", new SimplePaginationViewModel
            {
                TotalPages = Model.Posts.TotalPages,
                CurrentPage = Model.Posts.CurrentPage,
                NextUrl = Url.Action("GetExploreView", "Explore", new { pageNumber = Model.Posts.CurrentPage + 1 }),
                PreviousUrl = Url.Action("GetExploreView", "Explore", new { pageNumber = Model.Posts.CurrentPage - 1 })
            })
        }
    </div>
</div>